<?php
// $Id$
/**
 * @file
 * Variable API module
 */

/**
 * Implementation of hook_boot()
 * 
 * Though we don't do anything here, we ensure the module is loaded at boot stage
 * for other modules (like variable_realm) to be able to use the API
 */
function variable_boot() {
}

/**
 * Implementation of hook_flush_caches()
 */
function variable_flush_caches() {
  return array('cache_variable');
}

/**
 * Check access to variable
 * 
 * @param $variable
 *   Variable name or info array
 */
function variable_access($variable, $account = NULL) {
  $account = $account ? $account : $GLOBALS['user'];
  $variable = variable_variable($variable);
  return $variable && (!empty($variable['access']) && user_access($variable['access'], $account) || user_access('administer site configuration', $account));
}

/**
 * Get value for simple scalar variable
 * 
 * @param $variable
 *   Variable name or array data
 * @param $options
 *   Options array, it may have the following elements
 *   - language => Language object
 *   - default => Default value if not set
 */
function variable_get_value($variable, $options = array()) {
  $options = variable_options($options);
  $variable = variable_variable($variable, $options);
  if (!empty($variable['multiple'])) {
    return variable_get_multiple($variable, $options);
  }
  else {
    $value = variable_get($variable['name'], NULL);
    if (isset($value)) {
      return $value;
    }
    else {
      return isset($options['default']) ? $options['default'] : variable_get_default($variable, $options);
    }
  }
}

/**
 * Get variable default
 * 
 * @param $variable
 *   Variable name or variable information
 */
function variable_get_default($variable, $options = array()) {
  $variable = variable_variable($variable, $options);
  if (isset($variable['default callback'])) {
    return call_user_func($variable['default callback'], $variable, variable_options($options));
  }
  elseif (isset($variable['default'])) {
    return $variable['default'];
  }
  return NULL;
}

/**
 * Set variable value
 * 
 * This basically sets the variable but also invokes hook_variable_update
 */
function variable_set_value($name, $value, $options = array()) {
  $old_value = variable_get($name, NULL);
  variable_set($name, $value);
  module_invoke_all('variable_update', $name, $value, $old_value);
}

/**
 * Get variable information
 * 
 * Variable information is collected from modules and cached by language
 * 
 * @param $name
 *   Optional variable name. Will return all if no name.
 */
function variable_get_info($name = NULL, $options = array()) {
  static $info;
  $options = variable_options($options);
  $langcode = $options['langcode'];
  if (!isset($info)) {
    $info = &drupal_static('variable_info');
  }
  if (!isset($info[$langcode])) {
    if ($cache = variable_cache_get('variable_info', $langcode)) {
      $info[$langcode] = $cache->data;
    }
    else {
      variable_include();
      $info[$langcode] = variable_build_info($options);
      variable_cache_set('variable_info', $info[$langcode], $langcode);
    }
  }
  if ($name) {
    return isset($info[$langcode][$name]) ? $info[$langcode][$name] : array();
  }
  else {
    return $info[$langcode];
  }
}

/**
 * Get value from variable cache
 */
function variable_cache_get($name, $langcode = 'default') {
  return cache_get($name . ':' . $langcode, 'cache_variable');
}

/**
 * Set value in cache
 */
function variable_cache_set($name, $data, $langcode = 'default') {
  cache_set($name . ':' . $langcode, $data, 'cache_variable');
}

/**
 * Clear cache
 */
function variable_cache_clear($name = NULL, $langcode = NULL) {
  if ($name || $langcode) {
    $cids = array(
      $name ? $name : '%',
      $langcode ? $langcode : '%',
    );
    db_query("DELETE FROM {cache_variable} WHERE cid LIKE :cid", array(':cid' => implode(':', $cids)));
  }
  else {
    db_query("TRUNCATE TABLE {cache_variable}");
  }
}

/**
 * Format printable value
 * 
 * @param $variable
 * 
 */
function variable_format_value($variable, $options = array()) {
  variable_include();
  $variable = variable_build($variable, $options);
  $value = variable_get_value($variable['name'], $options);
  if (isset($value)) {
    return !empty($variable['format callback']) ? call_user_func($variable['format callback'], $value, $variable, $options) : check_plain($value);
  }
  else {
    return isset($variable['empty']) ? $variable['empty'] : t('Empty');
  }
}

/**
 * Implements hook_hook_info().
 */
function variable_hook_info() {
  $hooks['variable_info'] = array(
    'group' => 'variable',
  );
  $hooks['variable_group_info'] = array(
    'group' => 'variable',
  );
  $hooks['variable_type_info'] = array(
    'group' => 'variable',
  );
  $hooks['variable_option_list'] = array(
    'group' => 'variable',
  );
  return $hooks; 
}

/**
 * Get global language object.
 * 
 * Initialize the language system if needed as we absolutely need a language here
 */
function variable_language() {
  global $language;
  if (!isset($language)) {
    drupal_bootstrap(DRUPAL_BOOTSTRAP_LANGUAGE);
  }
  return $language; 
}

/**
 * Get multiple variable values
 * 
 * @param $variable
 *   Variable name or variable array
 * @return array
 *   Key, value pairs for each sub-variable
 */
function variable_get_multiple($variable, $options = array()) {
  variable_include();
  $values = array();
  $variable = variable_build($variable, $options);
  if ($variable && !empty($variable['multiple'])) {
    $default = variable_get_default($variable, $options);
    foreach (array_keys($variable['multiple']) as $key) {
      $value = variable_get($variable['name'] . '_' . $key);
      if (!isset($value) && isset($default)) {
        if (is_array($default)) {
          $value = isset($default[$key]) ? $default[$key] : NULL;
        }
        else {
          $value = $default;
        }
      }
      $values[$key] = $value;
    }
  }
  return $values;
}

/**
 * Normalize variable options
 * 
 * Will fill the following values if not present in the parameters
 * - langcode, Language code
 * - language, Language object
 */
function variable_options($options = array()) {
  if (!empty($options['language'])) {
    $options['langcode'] = $options['language']->language;
  }
  elseif (!empty($options['langcode']) && ($list = language_list()) && isset($list[$options['langcode']])) {
    $options['language'] = $list[$options['langcode']];
  }
  else {
    $language = variable_language();
    $options['language'] = $language;
    $options['langcode'] = $language->language;
  }
  return $options;  
}

/**
 * Include extended API
 */
function variable_include($name = 'variable') {
  static $included;
  if (!isset($included[$name])) {
    module_load_include('inc', 'variable', $name);
  }
}

/**
 * Form for variable list
 * 
 * @param $list
 *   Variable name or list of variable names
 */
function variable_edit_form($form, $form_state, $list) {
  variable_include();
  variable_include('variable.form');
  $list = is_array($list) ? $list : array($list);
  $form = array();
  foreach ($list as $name) {
    if ($variable = variable_get_info($name)) {
      $form[$name] = variable_form_element($variable);
    }
  }
  return system_settings_form($form);
}

/**
 * Implements hook_modules_uninstalled().
 */
function variable_modules_uninstalled($modules) {
  variable_include();
  array_map('variable_module_uninstall', $modules);
  variable_cache_clear();
}

/**
 * Normalize variable data
 */
function variable_variable($variable, $options = array()) {
  if (is_array($variable)) {
    return $variable;
  }
  elseif ($variable = variable_get_info($variable, $options)) {
    return $variable;
  }
  else {
    return array('name' => $variable, 'type' => 'default');
  }
}