<?php
/**
 * @file
 * Variable API module - Admin UI
 */

/**
 * Implementation of hook_menu().
 */
function variable_admin_menu() {
  $items['admin/settings/variable'] = array(
    'title' => 'Variables',
    'description' => 'Edit and delete site variables.',
    'page callback' => 'variable_admin_page_overview',
    'access arguments' => array('administer site configuration'),
    'file' => 'variable_admin.pages.inc',
  );
  $items['admin/settings/variable/group'] = array(
    'title' => 'By group',
    'description' => 'Variables by group.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/variable/group/%'] = array(
    'title' => 'Variables group',
    'description' => 'Edit and delete group variables.',
    'page callback' => 'variable_admin_page_group',
    'page arguments' => array(4),
    'access arguments' => array('administer site configuration'),
    'file' => 'variable_admin.pages.inc',
  );  
  $items['admin/settings/variable/modules'] = array(
    'title' => 'By module',
    'description' => 'Variables by module.',
    'page callback' => 'variable_admin_page_modules',
    'access arguments' => array('administer site configuration'),
    'file' => 'variable_admin.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/variable/undefined'] = array(
    'title' => 'Undefined',
    'description' => 'Unknown variables.',
    'page callback' => 'variable_admin_page_undefined',
    'access arguments' => array('administer site configuration'),
    'file' => 'variable_admin.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/variable/edit/%'] = array(
    'title' => 'Edit variable',
    'page callback' => 'variable_admin_page_edit',
    'page arguments' => array(4),
    'access callback' => 'variable_access',
    'access arguments' => array(4),
    'file' => 'variable_admin.pages.inc',
  );  
  return $items;
}


