<?php
/**
 * @file
 * Variable Realms Admin module
 */

/**
 * Query parameter prefix for realm switcher.
 */
define('VARIABLE_REALM_SELECTOR_QUERY_PARAM_PREFIX', 'realm-');

/**
 * Implements hook_menu().
 */
function variable_realm_admin_menu() {
  $items['admin/config/system/variable/realm'] = array(
    'title' => 'Realms',
    'description' => 'Configure realms.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_realm_admin_realm_overview'),
    'file' => 'variable_realm_admin.pages.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/system/variable/realm/overview'] = array(
    'title' => 'Overview',
    'description' => 'Configure realms.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );
  foreach (variable_realm_list() as $realm => $title) {
    $items['admin/config/system/variable/realm/' . $realm] = array(
      'title callback' => 'variable_realm_admin_realm_title',
      'title arguments' => array($realm),
      'description' => 'Configure realm variables.',
      'page callback' => 'variable_realm_admin_realm_info',
      'page arguments' => array($realm),
      'access callback' => 'variable_realm_admin_access',
      'access arguments' => array($realm),
      'file' => 'variable_realm_admin.pages.inc',
      'type' => MENU_LOCAL_TASK,
    );
  }
  $items['admin/config/system/variable/realm/%/edit'] = array(
    'title' => 'Edit',
    'description' => 'Edit realm variables.',
    'page callback' => 'variable_realm_admin_realm_edit',
    'page arguments' => array(5),
    'access callback' => 'variable_realm_admin_access',
    'access arguments' => array(5, 'select'),
    'file' => 'variable_realm_admin.pages.inc',
    //'file path' => drupal_get_path('module', 'variable_realm'),
    //'type' => MENU_CALLBACK,
  );
  $items['admin/config/system/variable/realm/%/configure'] = array(
    'title' => 'Configure',
    'description' => 'Configure realm variables.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_realm_select_variables_form', 5),
    'access callback' => 'variable_realm_admin_access',
    'access arguments' => array(5, 'select'),
    'file' => 'variable_realm.form.inc',
    'file path' => drupal_get_path('module', 'variable_realm'),
    //'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Check permission for administering realm
 */
function variable_realm_admin_access($realm_name, $property = 'title') {
  if ($info = variable_realm_info($realm_name)) {
    return !empty($info[$property]) && user_access('administer site configuration');
  }
}

/**
 * Retrieve title of given realm.
 */
function variable_realm_admin_realm_title($realm) {
  $info = variable_realm_info($realm);
  return isset($info['title']) ? $info['title'] : $realm;
}

/**
 * Implements hook_module_implements_alter().
 *
 * Move variable_realm_admin_form_alter() to the end of the list to be able to
 * act on variables added during hook_form_alter().
 *
 * @param $implementations
 *   All implementations of the given hook.
 * @param $hook
 *   Name of the hook.
 */
/*
function variable_realm_admin_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // move own hook to end
    $group = $implementations['variable_realm_admin'];
    unset($implementations['variable_realm_admin']);
    $implementations['variable_realm_admin'] = $group;

    // remove i18n_variable_form_alter, because we take care of things now :)
    unset($implementations['i18n_variable']);
  }
}
*/

